/* ---- Additions FOOD_QUALITY — coller AVANT le "};" de l'objet FOOD_QUALITY (data.js). 98 entrées, clés = noms réellement loggés (matchées via fqKey). ---- */
  "avocat":{p:0,n:1,w:0},
  "baguette":{p:0,n:2,w:0},
  "balisto":{p:0,n:3,w:FQ_SUCRE},
  "barre gerlinea":{p:0,n:3,w:0},
  "battonets surimi":{p:1,n:3,w:0},
  "blanc de poulet":{p:1,n:1,w:0},
  "boule de glace":{p:0,n:3,w:FQ_SUCRE},
  "bout de pain":{p:0,n:2,w:0},
  "brioche au chocolat":{p:0,n:3,w:FQ_SUCRE},
  "brownie":{p:0,n:3,w:FQ_SUCRE},
  "camembert":{p:1,n:2,w:0},
  "camembert rotis":{p:1,n:2,w:0},
  "cannelet":{p:0,n:3,w:FQ_SUCRE},
  "chartreuse":{p:0,n:3,w:FQ_ALCOOL},
  "chausson au pomme":{p:0,n:3,w:FQ_SUCRE},
  "chips":{p:0,n:3,w:0},
  "chorizette":{p:1,n:3,w:FQ_CHARCUT},
  "compote de pomme":{p:0,n:2,w:0},
  "compote peche":{p:0,n:2,w:0},
  "compote peche bonne maman":{p:0,n:2,w:FQ_SUCRE},
  "confiture":{p:0,n:3,w:FQ_SUCRE},
  "cookies industriels":{p:0,n:3,w:FQ_SUCRE},
  "cornet de glace 2 boules":{p:0,n:3,w:FQ_SUCRE},
  "courgette":{p:0,n:1,w:0},
  "croissant":{p:0,n:3,w:0},
  "eclaire au fruit":{p:0,n:3,w:FQ_SUCRE},
  "espadon":{p:1,n:1,w:FQ_MERCURE},
  "falafel unite":{p:2,n:2,w:0},
  "fougassette":{p:0,n:3,w:0},
  "ginger beer":{p:0,n:3,w:FQ_SUCRE},
  "grog":{p:0,n:2,w:FQ_ALCOOL},
  "huile d’olive":{p:0,n:1,w:0},
  "jambon (tranche)":{p:1,n:2,w:FQ_CHARCUT},
  "jambon sec":{p:1,n:3,w:FQ_CHARCUT},
  "jambonneau":{p:1,n:2,w:FQ_CHARCUT},
  "kebab":{p:1,n:3,w:0},
  "kinder bueno":{p:0,n:3,w:FQ_SUCRE},
  "legumes cuits":{p:0,n:1,w:0},
  "m&m’s":{p:0,n:3,w:FQ_SUCRE},
  "magnum de glace":{p:0,n:3,w:FQ_SUCRE},
  "merguez":{p:1,n:3,w:FQ_CHARCUT},
  "mini pizza":{p:0,n:3,w:0},
  "mozzarela":{p:1,n:2,w:0},
  "nectarine":{p:0,n:1,w:0},
  "oeuf dure":{p:1,n:1,w:0},
  "oignon rouge":{p:0,n:1,w:0},
  "omelette":{p:1,n:1,w:0},
  "pain au chocolat":{p:0,n:3,w:0},
  "pain au pepite de chocolat":{p:0,n:3,w:FQ_SUCRE},
  "pain d’epices":{p:0,n:3,w:FQ_SUCRE},
  "part de flan":{p:0,n:3,w:FQ_SUCRE},
  "part de tiramisu maison":{p:0,n:2,w:FQ_SUCRE},
  "pasteis de nata":{p:0,n:3,w:FQ_SUCRE},
  "patate douce":{p:0,n:1,w:0},
  "pate ble complet":{p:2,n:1,w:0},
  "pates au pesto":{p:2,n:2,w:0},
  "pates au pesto gruyere":{p:2,n:2,w:0},
  "pates semi complete":{p:2,n:1,w:0},
  "peche":{p:0,n:1,w:0},
  "pepsi zero sucre":{p:0,n:3,w:0},
  "perrier tranche":{p:0,n:1,w:0},
  "persil":{p:0,n:1,w:0},
  "pesto":{p:0,n:2,w:0},
  "petit pois":{p:2,n:1,w:0},
  "pinte biere":{p:0,n:2,w:FQ_ALCOOL},
  "pizza":{p:0,n:3,w:0},
  "pomme de terre":{p:0,n:1,w:0},
  "portion de frite":{p:0,n:3,w:0},
  "pudding":{p:0,n:3,w:FQ_SUCRE},
  "ravioli jambon cru":{p:1,n:3,w:FQ_CHARCUT},
  "riz coco":{p:2,n:2,w:0},
  "salade":{p:0,n:1,w:0},
  "salade de crudites":{p:0,n:1,w:0},
  "salade de tomates":{p:0,n:1,w:0},
  "san pellegrino citron":{p:0,n:3,w:FQ_SUCRE},
  "sandwich jambon beurre":{p:1,n:2,w:FQ_CHARCUT},
  "sandwich jambon fromage":{p:1,n:2,w:FQ_CHARCUT},
  "saucisse chipolata":{p:1,n:3,w:FQ_CHARCUT},
  "saucisse nature":{p:1,n:3,w:FQ_CHARCUT},
  "semoule":{p:2,n:1,w:0},
  "sirop fraise":{p:0,n:3,w:FQ_SUCRE},
  "soupe miso":{p:0,n:2,w:0},
  "surimi":{p:1,n:3,w:0},
  "sushi":{p:1,n:2,w:0},
  "taboule":{p:2,n:2,w:0},
  "taco":{p:0,n:3,w:0},
  "tarte myrtille":{p:0,n:3,w:FQ_SUCRE},
  "tartelette caramel noix de pecan":{p:0,n:3,w:FQ_SUCRE},
  "tartelette citron meringue":{p:0,n:3,w:FQ_SUCRE},
  "tartine de fromage":{p:1,n:2,w:0},
  "tartine pain beurre":{p:0,n:2,w:0},
  "tartine rillettes de thon":{p:1,n:2,w:0},
  "ti punch":{p:0,n:2,w:FQ_ALCOOL},
  "tisane":{p:0,n:1,w:0},
  "tisane sommeil":{p:0,n:1,w:0},
  "vin rouge":{p:0,n:2,w:FQ_ALCOOL},
  "yaourt soja cafe":{p:0,n:2,w:0},
  "yaourt soja noisette":{p:0,n:2,w:0},
